# .air.toml
# Config file for air: https://github.com/air-verse/air

# The working directory for the project.
root = "."
tmp_dir = "tmp"

[build]
  # The command to build the binary. The -buildvcs=false flag fixes the error.
  cmd = "go build -o ./tmp/main -buildvcs=false ."
  # The path to the built binary.
  bin = "./tmp/main"
  # Watch these file extensions.
  include_ext = ["go", "tpl", "tmpl", "html", "css"]
  # Ignore these directories.
  exclude_dir = ["assets", "tmp", "vendor"]
  # Log name for the build process.
  log = "air_build.log"